sudo: required
addons:
  apt:
    packages:
    - wput
services:
  - docker
before_install:
  - docker pull yshalsager/cyanogenmod:latest
before_script:
- cd $HOME && mkdir twrp
- wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-6.0.1-20180502/omni_twrp-6.0.1-20180502-norepo.tar.lzma
  -O $HOME/twrp.tar.lzma
- tar --lzma -xf twrp.tar.lzma --directory $HOME/twrp/ && rm twrp.tar.lzma
script:
  - cd $HOME/twrp/ && git clone https://github.com/ZeoRexDevs/twrp_device_WALTON_Primo_RX5.git device/WALTON/Primo_RX5
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    cd /home/cmbuild/twrp/
    source build/envsetup.sh 1>/dev/null && lunch omni_Primo_RX5-eng 1>/dev/null && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/Primo_RX5/recovery.img $HOME/twrp/TWRP-$version-Primo_RX5-$(date +"%Y%m%d").img
  - wput $HOME/twrp/TWRP-$version-Primo_RX5-$(date +"%Y%m%d").img ftp://"$FTPUser":"$FTPPass"@"$FTPHost"/
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "rokibhasansagar"
  - git config --local user.email "10854164+rokibhasansagar@users.noreply.github.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: ZeoRexDevs/twrp_device_WALTON_Primo_RX5
    branch: master
notifications:
  email:
  - rokibhasansagar2014@outlook.com
